[package]
name = "oqs"
version = "0.1.0"
authors = ["msizanoen1 <qtmlabs@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liboqs-sys = { path = "../liboqs-sys" }
failure = "0.1.6"
